### PR TITLE
added sonar scanner cli dockderfile

### PR DESCRIPTION
**Pull request by imran-awan1**

### CODE REVIEW

**Comment by mogaal** [comment]
Why another Dockerfile? And also why it is including kops, helm, terraform, etc?

**Review by digitalronin — CHANGES_REQUESTED** [review]
If this is a docker image dedicated to running sonarqube, I think there's a bunch of stuff that could be removed from this, isn't there? (e.g. (but not only) the concourse terraform provider).

I'd prefer this to be as slim and simple as it can be, so that it's easier to maintain in the future.

**Comment by imran-awan1** [comment]
There is a sonar cli image but we would still need to add to the base to include ruby, kubectl etc. There is a bunch of stuff we don't need but I left it here incase its needed in future. But I guess it would make more sense to add as and when needed. So I'll slim it down further.

**Comment by imran-awan1** [comment]
@mogaal - A new Dockerfile added as this is independent to tools image.

**Comment by imran-awan1** [comment]
closed as the sonar qube dockerfile is now to its own repo.

**Pull request closed without merging**
